<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\DBI.Controller.Core\DBI.Controller.Core.csproj" />
    <ProjectReference Include="..\..\..\DBI.Drivers\DBI.Drivers.Modbus\DBI.Drivers.Modbus.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
