using System.Security.Cryptography;
using System.Text;
using DBI.Controller.Studio.Core.Models;
using RuntimeTagDataType = DBI.Controller.Core.Models.TagDataType;
using RuntimeTagDirection = DBI.Controller.Core.Models.TagDirection;
using RuntimeTagRoute = DBI.Controller.Core.Models.TagRoute;

namespace DBI.Controller.Studio.Core.Services;

public record CodeGenerationResult(string FilePath, string Text, bool Changed);

public sealed class IoCodeGenerator
{
    public const string GeneratedFileName = "IO.g.cs";
    private const string HeaderPrefix = "// tag-hash: ";

    public string GetGeneratedFilePath(DbiProject project) =>
        Path.Combine(project.ProjectDirectory, ProjectService.GeneratedFolder, GeneratedFileName);

    public CodeGenerationResult WriteIfChanged(DbiProject project)
    {
        string filePath = GetGeneratedFilePath(project);
        string text = Generate(project);

        Directory.CreateDirectory(Path.GetDirectoryName(filePath)!);

        if (File.Exists(filePath) && string.Equals(File.ReadAllText(filePath), text, StringComparison.Ordinal))
            return new CodeGenerationResult(filePath, text, false);

        File.WriteAllText(filePath, text, Encoding.UTF8);
        return new CodeGenerationResult(filePath, text, true);
    }

    public bool NeedsRegeneration(DbiProject project)
    {
        string filePath = GetGeneratedFilePath(project);
        if (!File.Exists(filePath)) return true;

        string header = File.ReadLines(filePath).FirstOrDefault(l => l.StartsWith(HeaderPrefix, StringComparison.Ordinal))
            ?? string.Empty;

        return !string.Equals(header, HeaderPrefix + ComputeTagHash(project), StringComparison.Ordinal);
    }

    public string Generate(DbiProject project)
    {
        var sb = new StringBuilder();
        string hash = ComputeTagHash(project);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     File này do DBI.Studio sinh tự động từ Tag Table.");
        sb.AppendLine("//     MỌI THAY ĐỔI THỦ CÔNG SẼ BỊ GHI ĐÈ khi build lại.");
        sb.AppendLine($"//     Nguồn: {Path.GetFileName(project.ProjectFilePath)}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine(HeaderPrefix + hash);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace DBI.Controller.SDK.IO;");
        sb.AppendLine();
        sb.AppendLine("public partial class IOContainer");
        sb.AppendLine("{");

        foreach (var tag in project.TagTables.SelectMany(t => t.Tags))
        {
            string summary = BuildSummary(tag);
            if (!string.IsNullOrWhiteSpace(summary))
            {
                sb.AppendLine($"    /// <summary>{EscapeXml(summary)}</summary>");
            }

            string typeName = tag.DataType switch
            {
                Models.TagDataType.Bool => "bool",
                Models.TagDataType.Int => "int",
                Models.TagDataType.Real => "float",
                _ => "bool"
            };

            string getter = tag.DataType switch
            {
                Models.TagDataType.Bool => "GetBool",
                Models.TagDataType.Int => "GetInt",
                Models.TagDataType.Real => "GetFloat",
                _ => "GetBool"
            };

            string setter = tag.DataType switch
            {
                Models.TagDataType.Bool => "SetBool",
                Models.TagDataType.Int => "SetInt",
                Models.TagDataType.Real => "SetFloat",
                _ => "SetBool"
            };

            string propName = SanitizePropertyName(tag.Name);
            if (tag.Direction == Models.TagDirection.Input)
            {
                sb.AppendLine($"    public {typeName} {propName} => {getter}(\"{tag.Name}\");");
            }
            else
            {
                sb.AppendLine(
                    $"    public {typeName} {propName} {{ get => {getter}(\"{tag.Name}\"); set => {setter}(\"{tag.Name}\", value); }}");
            }

            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string SanitizePropertyName(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return "UnnamedTag";
        var sb = new StringBuilder();
        foreach (char c in name.Trim())
        {
            if (char.IsLetterOrDigit(c) || c == '_') sb.Append(c);
            else sb.Append('_');
        }
        string result = sb.ToString();
        if (result.Length == 0) return "UnnamedTag";
        if (char.IsDigit(result[0])) result = "_" + result;
        return result;
    }

    public IReadOnlyList<RuntimeTagRoute> ExportRoutes(DbiProject project) =>
        project.TagTables
            .SelectMany(t => t.Tags)
            .Where(t => t.Direction != Models.TagDirection.Memory)
            .Select(t => new RuntimeTagRoute(
                t.Name,
                t.DataType switch
                {
                    Models.TagDataType.Bool => RuntimeTagDataType.Bool,
                    Models.TagDataType.Int => RuntimeTagDataType.Int,
                    Models.TagDataType.Real => RuntimeTagDataType.Real,
                    _ => RuntimeTagDataType.Bool
                },
                t.Direction switch
                {
                    Models.TagDirection.Input => RuntimeTagDirection.Input,
                    Models.TagDirection.Output => RuntimeTagDirection.Output,
                    _ => RuntimeTagDirection.Memory
                },
                t.Device,
                t.Address))
            .ToList();

    private static string BuildSummary(Tag tag)
    {
        if (!string.IsNullOrWhiteSpace(tag.Comment)) return tag.Comment.Trim();
        if (tag.Direction == Models.TagDirection.Memory) return "Biến nhớ nội bộ";
        return string.IsNullOrWhiteSpace(tag.Device) ? string.Empty : $"Tag {tag.Direction} trên thiết bị {tag.Device}";
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);

    private static string ComputeTagHash(DbiProject project)
    {
        string normalized = string.Join("\n",
            project.TagTables.SelectMany(t => t.Tags)
                .Select(t => $"{t.Name}|{t.DataType}|{t.Direction}|{t.Device}|{t.Comment}"));

        return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(normalized)));
    }
}
